def search_word():
    """
    A dictionary application for Web3 and Base Builds terms.
    Users can look up the meanings of over 100 terms related to Web3.
    """
    # Predefined dictionary with over 100 terms and meanings
    dictionary_data = {
        "blockchain": "A digital ledger technology that records transactions across many computers.",
        "smart contract": "A self-executing contract with the terms of the agreement directly written into code.",
        "NFT": "A non-fungible token representing ownership of a unique digital item.",
        "DAO": "A decentralized autonomous organization governed by its community of members.",
        "cryptography": "The practice of securing communication and information through encryption.",
        "staking": "The process of locking up cryptocurrency to earn rewards or secure a network.",
        "token": "A digital asset issued on a blockchain.",
        "gas fees": "The fees paid to perform transactions on a blockchain.",
        "mining": "The process of validating and recording transactions on a blockchain.",
        "consensus": "The mechanism used by blockchain networks to agree on the validity of transactions.",
        "hash": "A unique string of characters generated by a cryptographic function.",
        "ledger": "A record of all transactions on a blockchain.",
        "decentralization": "The process of distributing control and decision-making away from a central authority.",
        "wallet": "A digital tool used to store and manage cryptocurrency.",
        "private key": "A secret key used to access and manage cryptocurrency funds.",
        "public key": "A cryptographic key that can be shared publicly to receive transactions.",
        "ERC-20": "A standard for creating fungible tokens on the Ethereum blockchain.",
        "ERC-721": "A standard for creating non-fungible tokens (NFTs) on the Ethereum blockchain.",
        "metaverse": "A virtual world where users can interact, socialize, and conduct business.",
        "layer 2": "A scaling solution built on top of a blockchain to improve speed and reduce costs.",
        "mainnet": "The primary network where actual transactions occur.",
        "testnet": "A testing environment for blockchain developers.",
        "node": "A computer that participates in a blockchain network.",
        "peer-to-peer": "A network design where participants connect directly to each other.",
        "dApp": "A decentralized application that runs on a blockchain.",
        "governance": "The decision-making process within a blockchain or DAO.",
        "protocol": "A set of rules governing blockchain operations.",
        "interoperability": "The ability of different blockchains to communicate and share data.",
        "sharding": "A method of partitioning a blockchain to improve scalability.",
        "fork": "A change in the protocol of a blockchain network.",
        "airdrop": "A distribution of free cryptocurrency or tokens to users.",
        "ICO": "Initial Coin Offering, a way to raise funds for a new cryptocurrency project.",
        "whitelist": "A list of approved participants for an ICO or NFT mint.",
        "rug pull": "A scam where developers abandon a project and steal investors' funds.",
        "yield farming": "The practice of earning rewards by lending or staking cryptocurrency.",
        "liquidity pool": "A pool of funds locked in a smart contract to facilitate trading.",
        "DEX": "Decentralized exchange, a platform for trading cryptocurrency without intermediaries.",
        "CEX": "Centralized exchange, a platform for trading cryptocurrency managed by a central authority.",
        "fiat": "Traditional government-issued currency, such as USD or EUR.",
        "web3": "The decentralized internet powered by blockchain technology.",
        "dID": "Decentralized identity, a self-sovereign identity system based on blockchain.",
        "cross-chain": "The ability to transfer assets or data between different blockchains.",
        "oracle": "A service that provides external data to a blockchain.",
        "zk-SNARKs": "Zero-Knowledge Succinct Non-Interactive Arguments of Knowledge, used for privacy on blockchains.",
        "DeFi": "Decentralized finance, financial services on blockchain without intermediaries.",
        "hot wallet": "A cryptocurrency wallet connected to the internet.",
        "cold wallet": "A cryptocurrency wallet stored offline for security.",
        "stablecoin": "A cryptocurrency pegged to a stable asset like USD.",
        "web2": "The traditional, centralized internet.",
        "web1": "The early, read-only internet.",
        "POW": "Proof of Work, a consensus mechanism used by Bitcoin.",
        "POS": "Proof of Stake, a consensus mechanism using validators instead of miners.",
        "airnode": "A server running an oracle node for providing external data.",
        "burning": "The process of permanently removing cryptocurrency from circulation.",
        "governance token": "A token used for voting on decisions in a blockchain network or DAO.",
        "tokenomics": "The economic structure of a token.",
        "roadmap": "A planned timeline for a blockchain project's development.",
        "whale": "An individual or entity holding a large amount of cryptocurrency.",
        "DEX aggregator": "A tool that finds the best prices across decentralized exchanges.",
        "validator": "A participant in a blockchain network responsible for verifying transactions.",
        "miner": "A participant in a blockchain network responsible for mining blocks.",
        "hashrate": "The computational power of a blockchain network.",
        "faucet": "A website that gives away small amounts of cryptocurrency for free.",
        "dust": "A small amount of cryptocurrency left in a wallet after a transaction.",
        "seed phrase": "A set of words used to recover a cryptocurrency wallet.",
        "airdrops": "Promotional giveaways of cryptocurrency to users.",
        "block explorer": "A tool for viewing blockchain transactions.",
        "degen": "An investor who takes high risks in the cryptocurrency market.",
        "hashing algorithm": "The algorithm used to generate a unique hash for a blockchain.",
        "layer 1": "The base layer of a blockchain network.",
        "memecoin": "A cryptocurrency created as a joke or based on an internet meme.",
        "non-custodial": "A type of wallet or service where users retain control of their private keys.",
        "slippage": "The difference between the expected and actual price of a trade.",
        "supply cap": "The maximum number of tokens that will ever exist for a cryptocurrency.",
        "testnet faucet": "A faucet that provides free tokens for testing on a blockchain's testnet.",
        "token burn": "The process of destroying tokens to reduce supply.",
        "wrapped token": "A token representing another cryptocurrency on a different blockchain."
    }

    print("\nWelcome to the Web3 Lexicon Explorer!")
    print("Type a word to look up its meaning or type 'exit' to quit.")

    while True:
        # Get user input
        word = input("\nEnter a word: ").strip().lower()

        # Check if user wants to exit
        if word == "exit":
            print("\nThank you for using the Web3 Lexicon Explorer. Goodbye!")
            break

        # Look up the word in the dictionary
        meaning = dictionary_data.get(word)
        if meaning:
            print(f"\nMeaning of '{word}': {meaning}")
        else:
            print(f"\nSorry, '{word}' is not in the dictionary. Try another word.")

# Run the dictionary app
if __name__ == "__main__":
    search_word()
